files:
  - source: /*.json
    translation: /crowdin_translations/%locale_with_underscore%/%original_file_name%
  - source: /*.md
    translation: /md_translations/%locale%/%locale%-%original_file_name%
